# Generated by Django 5.1.3 on 2024-11-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=30)),
                ('precio', models.IntegerField(max_length=6)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
